### ISSUE TITLE
Wrong field

### ISSUE THREAD

**Issue by stablestream** [quotequack/forcepaste#1]
The call to thread::sleep(Duration::from_secs(2)) freezes the GUI for 2 seconds instead of buffering the keyboard, making the application unresponsive during that time.

**Comment by quotequack** [comment]
This is an issue that comes with the sleep function and it is a very tiny issue that does not impact users that much. Fixing it would not be worth it. Thank you though

**Comment by stablestream** [comment]
Even though it is a small issue it can be fixed easily :)

![image](https://github.com/user-attachments/assets/6da864be-4d13-4aff-a576-495e1e2ffde8)
